### PR TITLE
Canonical error msg for noargs jj 768

### PR DESCRIPTION
**Pull request by ghost**
Fage.error with canonical error message in absence of error arguments all ready to go.

Corrected a .d.ts typing error with Fage#run function as well (was missing optional input and meta args so we had a hacks in converlens email test code).

@cayuu Just a reminder since even though it's your code, this is an `npm install` job.
Would you please pull down and run `npm test` also.
A quick review of the test code & diff vs original should give you a pretty good heads up on what's happened.

One other thing, in `error.js` the `new Error(..)` is now constructed with the message argument. You will notice a slight difference in how the `message` property was provided via an assignment statement.

Anyway, really hope this PR meets what you were hoping for.

### CODE REVIEW

**Comment by indiescripter** [comment]
Damm, looks like there might be a bug. Will have to look at tomorrow.

Manually copied updated Fage over into converlens/server/node_modules.

Even though all the Fage tests pass, some converlens tests now fail, for example:

```
 FAIL  tests/httpapi/system.func.spec.ts (6.344s)
  ● system › GET /test-404 receives error payload

    expect(received).toEqual(expected)

    Expected value to equal:
      {"debug": {"error": {"message": "Resource not found: /test-404", "status": 404, "type": "Not Found"}, "errorMessage": "Resource not found: /test-404"}, "message": "Resource not found: /test-404", "status": 404}
    Received:
      {"debug": {"error": {"status": 404, "type": "Not Found"}, "errorMessage": "Resource not found: /test-404"}, "message": "Resource not found: /test-404", "status": 404}

    Difference:

    - Expected
    + Received
```

**Comment by cayuu** [comment]
Hey Justin - reviewed the code and it looks good. I can't explain why copying these changes over would switch `message` out with `errorMessage`, although otherwise the messages are the same. I suspect it might be something not quite 'catching' at the Converlens error reporter level but I can't dig too deep on this for now - on the surface, this should work. Sorry that's not more helpful ;)

**Comment by indiescripter** [comment]
All good now. Fixed the error message quirk.
Manually copied over into converlens/server/node_modules and tests passed 100% over there.
Have also updated npm package dependencies.
Reckon it's a goer so over to you for final review and publishing as version 2.3.0
(package.json & package-lock.json both updated)

Memo: you might still want to get rid of Bluebird one day.

**Review by cayuu — APPROVED** [review]
Looking good! I'll merge this all in and publish tmrw. Thanks Justin :)

**Comment by indiescripter** [comment]
Clint, as per Skype chat just now, this is a copy of the TypeScript version of Fage's error.js that I used to "prove" the code. You may wish to save this somewhere in case Fage ever gets converted from JS to TS.

**error.ts**
```
interface ErrorOptions {
  status?: number;
  type?: string;
  message?: string;
  code?: number | string;
  debug?: any;
  errors?: any;
}

interface ErrorOptionsAll {
  status: number;
  type: string;
  message?: string;
  code?: number | string;
  debug?: any;
  errors?: any;
}

interface FageError extends Error {
  status: number;
  type: string;
  code?: number | string;
  debug?: any;
  errors?: any;
}

/**
 * Standardised rich error generator
 *
 * @param {Number} status The HTTP status code associated with the error
 * @param {String} type A unique type for this error eg. Validation, NotLoggedIn
 * @param {String} [message] The Error message (default: `type` param)
 * @param {String} [code] An app specific custom error code
 * @param {Mixed} [debug] Debug information for DEVELOPERS
 * @param {Object} [errors] Extra errors object
 *
 * @returns {Object} with {message, status, type, debug} fields
 */

function buildError (opts: string | ErrorOptions): FageError {
  if (typeof opts === 'string') {
    opts = { message: opts }
  }

  const { status, type, message, code, debug, errors } = opts

  if (!status) {
    throw new Error('MUST provide error builder `status` and `type` props')
  }

  // Note using Object.assign here for expediency as this method gets around some
  // TypeScript typing issues without a drama.
  // HOWEVER, as I found out this method causes some weird issues to do with Object.keys
  // on the `FageError` object. The way you have done this part of the code in Fage JS seems
  // to work better (i.e. new Error(0 followed by explicit assign err.message = message).
  // Accordingly I reverted the Fage error.js code to what you had already.
  return Object.assign(
    new Error(message || type),
    { status, type: type as string, code, debug, errors }
  )
}

function prebuild (status: number, type: string): (opts?: string | ErrorOptions) => FageError {
  const eo = { status, type }

  return function errorPartial (opts: string | ErrorOptions = {}) {
    if (typeof opts === 'string') {
      opts = { message: opts }
    }

    let pass = Object.assign({}, opts, eo)

    // Allow user specified type to override default
    if (opts.type) pass.type = opts.type

    return buildError(pass)
  }
}

/*
  Available error generators
*/

const create: (options: ErrorOptionsAll) => FageError = buildError
const badrequest: (opts?: ErrorOptions | string) => FageError = prebuild(400, 'Bad Request')
const unauthorized: (opts?: ErrorOptions | string) => FageError = prebuild(401, 'Unauthorized')
const forbidden: (opts?: ErrorOptions | string) => FageError = prebuild(403, 'Forbidden')
const notfound: (opts?: ErrorOptions | string) => FageError = prebuild(404, 'Not Found')
const conflict: (opts?: ErrorOptions | string) => FageError = prebuild(409, 'Conflict')
const ratelimit: (opts?: ErrorOptions | string) => FageError = prebuild(429, 'Too Many Requests')
const fatal: (opts?: ErrorOptions | string) => FageError = prebuild(500, 'Internal Server Error')
const unavailable: (opts?: ErrorOptions | string) => FageError = prebuild(503, 'Service Unavailable')

module.exports.create = create
module.exports.badrequest = badrequest
module.exports.unauthorized = unauthorized
module.exports.forbidden = forbidden
module.exports.notfound = notfound
module.exports.conflict = conflict
module.exports.ratelimit = ratelimit
module.exports.fatal = fatal
module.exports.unavailable = unavailable

console.log('badrequest("Foo")', badrequest("Foo"));
console.log('badrequest("Foo").message', badrequest("Foo").message);
console.log('badrequest("Foo").status', badrequest("Foo").status);
console.log('badrequest("Foo").type', badrequest("Foo").type);
console.log('badrequest("Foo").code', badrequest("Foo").code);
console.log('badrequest("Foo").debug', badrequest("Foo").debug);
console.log('badrequest("Foo").errors', badrequest("Foo").errors);
//console.log('unauthorized()', unauthorized());
//console.log('forbidden()', forbidden());
//console.log('notfound()', notfound());
//console.log('conflict()', conflict());
//console.log('ratelimit()', ratelimit());
//console.log('fatal()', fatal());
//console.log('unavailable()', unavailable());
```

**Pull request merged**
